// Generated by rstantools.  Do not edit by hand.

/*
    TelemetrySpace is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TelemetrySpace is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with TelemetrySpace.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.36.0-112-g93cda2f
#include <stan/model/model_header.hpp>
namespace model_COA_Tag_Integrated_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 71> locations_array__ =
  {" (found before start of program)",
  " (in 'COA_Tag_Integrated', line 25, column 2 to column 56)",
  " (in 'COA_Tag_Integrated', line 26, column 2 to column 25)",
  " (in 'COA_Tag_Integrated', line 28, column 2 to column 63)",
  " (in 'COA_Tag_Integrated', line 30, column 2 to column 63)",
  " (in 'COA_Tag_Integrated', line 36, column 3 to column 30)",
  " (in 'COA_Tag_Integrated', line 38, column 3 to column 14)",
  " (in 'COA_Tag_Integrated', line 40, column 3 to column 35)",
  " (in 'COA_Tag_Integrated', line 42, column 3 to column 30)",
  " (in 'COA_Tag_Integrated', line 45, column 3 to column 34)",
  " (in 'COA_Tag_Integrated', line 51, column 6 to column 79)",
  " (in 'COA_Tag_Integrated', line 49, column 20 to line 53, column 5)",
  " (in 'COA_Tag_Integrated', line 49, column 4 to line 53, column 5)",
  " (in 'COA_Tag_Integrated', line 48, column 19 to line 54, column 3)",
  " (in 'COA_Tag_Integrated', line 48, column 2 to line 54, column 3)",
  " (in 'COA_Tag_Integrated', line 60, column 10 to column 85)",
  " (in 'COA_Tag_Integrated', line 63, column 10 to column 45)",
  " (in 'COA_Tag_Integrated', line 58, column 23 to line 64, column 6)",
  " (in 'COA_Tag_Integrated', line 58, column 6 to line 64, column 6)",
  " (in 'COA_Tag_Integrated', line 57, column 20 to line 65, column 4)",
  " (in 'COA_Tag_Integrated', line 57, column 4 to line 65, column 4)",
  " (in 'COA_Tag_Integrated', line 56, column 20 to line 66, column 2)",
  " (in 'COA_Tag_Integrated', line 56, column 3 to line 66, column 2)",
  " (in 'COA_Tag_Integrated', line 71, column 2 to column 39)",
  " (in 'COA_Tag_Integrated', line 72, column 2 to column 26)",
  " (in 'COA_Tag_Integrated', line 78, column 6 to column 83)",
  " (in 'COA_Tag_Integrated', line 76, column 22 to line 79, column 5)",
  " (in 'COA_Tag_Integrated', line 76, column 4 to line 79, column 5)",
  " (in 'COA_Tag_Integrated', line 82, column 8 to column 84)",
  " (in 'COA_Tag_Integrated', line 80, column 22 to line 83, column 5)",
  " (in 'COA_Tag_Integrated', line 80, column 5 to line 83, column 5)",
  " (in 'COA_Tag_Integrated', line 75, column 20 to line 84, column 4)",
  " (in 'COA_Tag_Integrated', line 75, column 3 to line 84, column 4)",
  " (in 'COA_Tag_Integrated', line 74, column 20 to line 85, column 3)",
  " (in 'COA_Tag_Integrated', line 74, column 2 to line 85, column 3)",
  " (in 'COA_Tag_Integrated', line 3, column 2 to column 22)",
  " (in 'COA_Tag_Integrated', line 4, column 2 to column 22)",
  " (in 'COA_Tag_Integrated', line 5, column 2 to column 23)",
  " (in 'COA_Tag_Integrated', line 6, column 2 to column 23)",
  " (in 'COA_Tag_Integrated', line 7, column 2 to column 24)",
  " (in 'COA_Tag_Integrated', line 9, column 8 to column 12)",
  " (in 'COA_Tag_Integrated', line 9, column 14 to column 18)",
  " (in 'COA_Tag_Integrated', line 9, column 20 to column 25)",
  " (in 'COA_Tag_Integrated', line 9, column 2 to column 44)",
  " (in 'COA_Tag_Integrated', line 11, column 8 to column 13)",
  " (in 'COA_Tag_Integrated', line 11, column 15 to column 19)",
  " (in 'COA_Tag_Integrated', line 11, column 21 to column 26)",
  " (in 'COA_Tag_Integrated', line 11, column 2 to column 48)",
  " (in 'COA_Tag_Integrated', line 13, column 8 to column 12)",
  " (in 'COA_Tag_Integrated', line 13, column 2 to column 24)",
  " (in 'COA_Tag_Integrated', line 14, column 8 to column 12)",
  " (in 'COA_Tag_Integrated', line 14, column 2 to column 24)",
  " (in 'COA_Tag_Integrated', line 15, column 2 to column 21)",
  " (in 'COA_Tag_Integrated', line 16, column 2 to column 21)",
  " (in 'COA_Tag_Integrated', line 17, column 8 to column 13)",
  " (in 'COA_Tag_Integrated', line 17, column 2 to column 26)",
  " (in 'COA_Tag_Integrated', line 18, column 8 to column 13)",
  " (in 'COA_Tag_Integrated', line 18, column 2 to column 26)",
  " (in 'COA_Tag_Integrated', line 25, column 8 to column 13)",
  " (in 'COA_Tag_Integrated', line 25, column 15 to column 19)",
  " (in 'COA_Tag_Integrated', line 28, column 8 to column 12)",
  " (in 'COA_Tag_Integrated', line 28, column 14 to column 19)",
  " (in 'COA_Tag_Integrated', line 30, column 8 to column 12)",
  " (in 'COA_Tag_Integrated', line 30, column 14 to column 19)",
  " (in 'COA_Tag_Integrated', line 36, column 9 to column 14)",
  " (in 'COA_Tag_Integrated', line 36, column 16 to column 20)",
  " (in 'COA_Tag_Integrated', line 40, column 9 to column 13)",
  " (in 'COA_Tag_Integrated', line 40, column 15 to column 19)",
  " (in 'COA_Tag_Integrated', line 40, column 21 to column 26)",
  " (in 'COA_Tag_Integrated', line 42, column 9 to column 14)",
  " (in 'COA_Tag_Integrated', line 42, column 16 to column 20)"};
#include <stan_meta_header.hpp>
class model_COA_Tag_Integrated final : public model_base_crtp<model_COA_Tag_Integrated> {
private:
  int nind;
  int nrec;
  int ntime;
  int ntest;
  int ntrans;
  std::vector<std::vector<std::vector<int>>> y;
  std::vector<std::vector<std::vector<int>>> test;
  std::vector<double> recX;
  std::vector<double> recY;
  std::vector<double> xlim;
  std::vector<double> ylim;
  std::vector<double> testX;
  std::vector<double> testY;
public:
  ~model_COA_Tag_Integrated() {}
  model_COA_Tag_Integrated(stan::io::var_context& context__, unsigned int
                           random_seed__ = 0, std::ostream*
                           pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_COA_Tag_Integrated_namespace::model_COA_Tag_Integrated";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 35;
      context__.validate_dims("data initialization", "nind", "int",
        std::vector<size_t>{});
      nind = std::numeric_limits<int>::min();
      current_statement__ = 35;
      nind = context__.vals_i("nind")[(1 - 1)];
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "nind", nind, 0);
      current_statement__ = 36;
      context__.validate_dims("data initialization", "nrec", "int",
        std::vector<size_t>{});
      nrec = std::numeric_limits<int>::min();
      current_statement__ = 36;
      nrec = context__.vals_i("nrec")[(1 - 1)];
      current_statement__ = 36;
      stan::math::check_greater_or_equal(function__, "nrec", nrec, 0);
      current_statement__ = 37;
      context__.validate_dims("data initialization", "ntime", "int",
        std::vector<size_t>{});
      ntime = std::numeric_limits<int>::min();
      current_statement__ = 37;
      ntime = context__.vals_i("ntime")[(1 - 1)];
      current_statement__ = 37;
      stan::math::check_greater_or_equal(function__, "ntime", ntime, 0);
      current_statement__ = 38;
      context__.validate_dims("data initialization", "ntest", "int",
        std::vector<size_t>{});
      ntest = std::numeric_limits<int>::min();
      current_statement__ = 38;
      ntest = context__.vals_i("ntest")[(1 - 1)];
      current_statement__ = 38;
      stan::math::check_greater_or_equal(function__, "ntest", ntest, 0);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "ntrans", "int",
        std::vector<size_t>{});
      ntrans = std::numeric_limits<int>::min();
      current_statement__ = 39;
      ntrans = context__.vals_i("ntrans")[(1 - 1)];
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "ntrans", ntrans, 0);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("y", "nind", nind);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("y", "nrec", nrec);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("y", "ntime", ntime);
      current_statement__ = 43;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(nind),
          static_cast<size_t>(nrec), static_cast<size_t>(ntime)});
      y = std::vector<std::vector<std::vector<int>>>(nind,
            std::vector<std::vector<int>>(nrec,
              std::vector<int>(ntime, std::numeric_limits<int>::min())));
      {
        std::vector<int> y_flat__;
        current_statement__ = 43;
        y_flat__ = context__.vals_i("y");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= nrec; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= nind; ++sym3__) {
              stan::model::assign(y, y_flat__[(pos__ - 1)],
                "assigning variable y", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 43;
      stan::math::check_greater_or_equal(function__, "y", y, 0);
      current_statement__ = 44;
      stan::math::validate_non_negative_index("test", "ntest", ntest);
      current_statement__ = 45;
      stan::math::validate_non_negative_index("test", "nrec", nrec);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("test", "ntime", ntime);
      current_statement__ = 47;
      context__.validate_dims("data initialization", "test", "int",
        std::vector<size_t>{static_cast<size_t>(ntest),
          static_cast<size_t>(nrec), static_cast<size_t>(ntime)});
      test = std::vector<std::vector<std::vector<int>>>(ntest,
               std::vector<std::vector<int>>(nrec,
                 std::vector<int>(ntime, std::numeric_limits<int>::min())));
      {
        std::vector<int> test_flat__;
        current_statement__ = 47;
        test_flat__ = context__.vals_i("test");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= nrec; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= ntest; ++sym3__) {
              stan::model::assign(test, test_flat__[(pos__ - 1)],
                "assigning variable test", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 47;
      stan::math::check_greater_or_equal(function__, "test", test, 0);
      current_statement__ = 48;
      stan::math::validate_non_negative_index("recX", "nrec", nrec);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "recX", "double",
        std::vector<size_t>{static_cast<size_t>(nrec)});
      recX = std::vector<double>(nrec,
               std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 49;
      recX = context__.vals_r("recX");
      current_statement__ = 50;
      stan::math::validate_non_negative_index("recY", "nrec", nrec);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "recY", "double",
        std::vector<size_t>{static_cast<size_t>(nrec)});
      recY = std::vector<double>(nrec,
               std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 51;
      recY = context__.vals_r("recY");
      current_statement__ = 52;
      context__.validate_dims("data initialization", "xlim", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      xlim = std::vector<double>(2, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 52;
      xlim = context__.vals_r("xlim");
      current_statement__ = 53;
      context__.validate_dims("data initialization", "ylim", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      ylim = std::vector<double>(2, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 53;
      ylim = context__.vals_r("ylim");
      current_statement__ = 54;
      stan::math::validate_non_negative_index("testX", "ntest", ntest);
      current_statement__ = 55;
      context__.validate_dims("data initialization", "testX", "double",
        std::vector<size_t>{static_cast<size_t>(ntest)});
      testX = std::vector<double>(ntest,
                std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 55;
      testX = context__.vals_r("testX");
      current_statement__ = 56;
      stan::math::validate_non_negative_index("testY", "ntest", ntest);
      current_statement__ = 57;
      context__.validate_dims("data initialization", "testY", "double",
        std::vector<size_t>{static_cast<size_t>(ntest)});
      testY = std::vector<double>(ntest,
                std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 57;
      testY = context__.vals_r("testY");
      current_statement__ = 58;
      stan::math::validate_non_negative_index("alpha0", "ntime", ntime);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("alpha0", "nrec", nrec);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("sx", "nind", nind);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("sx", "ntime", ntime);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("sy", "nind", nind);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("sy", "ntime", ntime);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("p0", "ntime", ntime);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("p0", "nrec", nrec);
      current_statement__ = 66;
      stan::math::validate_non_negative_index("d", "nind", nind);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("d", "nrec", nrec);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("d", "ntime", ntime);
      current_statement__ = 69;
      stan::math::validate_non_negative_index("td", "ntest", ntest);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("td", "nrec", nrec);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (ntime * nrec) + 1 + (nind * ntime) + (nind * ntime);
  }
  inline std::string model_name() const final {
    return "model_COA_Tag_Integrated";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.36.0-112-g93cda2f",
             "stancflags = --allow-undefined"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_COA_Tag_Integrated_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto alpha0 =
        in__.template read_constrain_lub<
          std::vector<std::vector<local_scalar_t__>>, jacobian__>(-(5), 5,
          lp__, ntime, nrec);
      current_statement__ = 2;
      auto alpha1 =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 3;
      auto sx =
        in__.template read_constrain_lub<
          std::vector<std::vector<local_scalar_t__>>,
          jacobian__>(stan::model::rvalue(xlim, "xlim",
                        stan::model::index_uni(1)),
          stan::model::rvalue(xlim, "xlim", stan::model::index_uni(2)), lp__,
          nind, ntime);
      current_statement__ = 4;
      auto sy =
        in__.template read_constrain_lub<
          std::vector<std::vector<local_scalar_t__>>,
          jacobian__>(stan::model::rvalue(ylim, "ylim",
                        stan::model::index_uni(1)),
          stan::model::rvalue(ylim, "ylim", stan::model::index_uni(2)), lp__,
          nind, ntime);
      std::vector<std::vector<local_scalar_t__>> p0 =
        std::vector<std::vector<local_scalar_t__>>(ntime,
          std::vector<local_scalar_t__>(nrec, DUMMY_VAR__));
      local_scalar_t__ sigma = DUMMY_VAR__;
      std::vector<std::vector<std::vector<local_scalar_t__>>> d =
        std::vector<std::vector<std::vector<local_scalar_t__>>>(nind,
          std::vector<std::vector<local_scalar_t__>>(nrec,
            std::vector<local_scalar_t__>(ntime, DUMMY_VAR__)));
      std::vector<std::vector<local_scalar_t__>> td =
        std::vector<std::vector<local_scalar_t__>>(ntest,
          std::vector<local_scalar_t__>(nrec, DUMMY_VAR__));
      current_statement__ = 9;
      sigma = stan::math::sqrt((1 / (2 * alpha1)));
      current_statement__ = 14;
      for (int s = 1; s <= ntest; ++s) {
        current_statement__ = 12;
        for (int j = 1; j <= nrec; ++j) {
          current_statement__ = 10;
          stan::model::assign(td,
            stan::math::sqrt(
              (stan::math::square(
                 (stan::model::rvalue(testX, "testX",
                    stan::model::index_uni(s)) -
                 stan::model::rvalue(recX, "recX", stan::model::index_uni(j))))
              +
              stan::math::square(
                (stan::model::rvalue(testY, "testY",
                   stan::model::index_uni(s)) -
                stan::model::rvalue(recY, "recY", stan::model::index_uni(j)))))),
            "assigning variable td", stan::model::index_uni(s),
            stan::model::index_uni(j));
        }
      }
      current_statement__ = 22;
      for (int t = 1; t <= ntime; ++t) {
        current_statement__ = 20;
        for (int j = 1; j <= nrec; ++j) {
          current_statement__ = 18;
          for (int i = 1; i <= nind; ++i) {
            current_statement__ = 15;
            stan::model::assign(d,
              stan::math::sqrt(
                (stan::math::square(
                   (stan::model::rvalue(sx, "sx", stan::model::index_uni(i),
                      stan::model::index_uni(t)) -
                   stan::model::rvalue(recX, "recX",
                     stan::model::index_uni(j)))) +
                stan::math::square(
                  (stan::model::rvalue(sy, "sy", stan::model::index_uni(i),
                     stan::model::index_uni(t)) -
                  stan::model::rvalue(recY, "recY", stan::model::index_uni(j)))))),
              "assigning variable d", stan::model::index_uni(i),
              stan::model::index_uni(j), stan::model::index_uni(t));
            current_statement__ = 16;
            stan::model::assign(p0,
              stan::math::inv_logit(
                stan::model::rvalue(alpha0, "alpha0",
                  stan::model::index_uni(t), stan::model::index_uni(j))),
              "assigning variable p0", stan::model::index_uni(t),
              stan::model::index_uni(j));
          }
        }
      }
      {
        current_statement__ = 23;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(
                         stan::model::rvalue(alpha0, "alpha0",
                           stan::model::index_uni(ntime),
                           stan::model::index_uni(nrec)), 0, 2.5));
        current_statement__ = 24;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(alpha1, 0, 2.5));
        current_statement__ = 34;
        for (int t = 1; t <= ntime; ++t) {
          current_statement__ = 32;
          for (int j = 1; j <= nrec; ++j) {
            current_statement__ = 27;
            for (int s = 1; s <= ntest; ++s) {
              current_statement__ = 25;
              lp_accum__.add(stan::math::binomial_lpmf<propto__>(
                               stan::model::rvalue(test, "test",
                                 stan::model::index_uni(s),
                                 stan::model::index_uni(j),
                                 stan::model::index_uni(t)), ntrans,
                               (stan::model::rvalue(p0, "p0",
                                  stan::model::index_uni(t),
                                  stan::model::index_uni(j)) *
                               stan::math::exp((-(alpha1) *
                                 stan::math::square(
                                   stan::model::rvalue(td, "td",
                                     stan::model::index_uni(s),
                                     stan::model::index_uni(j))))))));
            }
            current_statement__ = 30;
            for (int i = 1; i <= nind; ++i) {
              current_statement__ = 28;
              lp_accum__.add(stan::math::binomial_lpmf<propto__>(
                               stan::model::rvalue(y, "y",
                                 stan::model::index_uni(i),
                                 stan::model::index_uni(j),
                                 stan::model::index_uni(t)), ntrans,
                               (stan::model::rvalue(p0, "p0",
                                  stan::model::index_uni(t),
                                  stan::model::index_uni(j)) *
                               stan::math::exp((-(alpha1) *
                                 stan::math::square(
                                   stan::model::rvalue(d, "d",
                                     stan::model::index_uni(i),
                                     stan::model::index_uni(j),
                                     stan::model::index_uni(t))))))));
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_COA_Tag_Integrated_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto alpha0 =
        in__.template read_constrain_lub<
          std::vector<std::vector<local_scalar_t__>>, jacobian__>(-(5), 5,
          lp__, ntime, nrec);
      current_statement__ = 2;
      auto alpha1 =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 3;
      auto sx =
        in__.template read_constrain_lub<
          std::vector<std::vector<local_scalar_t__>>,
          jacobian__>(stan::model::rvalue(xlim, "xlim",
                        stan::model::index_uni(1)),
          stan::model::rvalue(xlim, "xlim", stan::model::index_uni(2)), lp__,
          nind, ntime);
      current_statement__ = 4;
      auto sy =
        in__.template read_constrain_lub<
          std::vector<std::vector<local_scalar_t__>>,
          jacobian__>(stan::model::rvalue(ylim, "ylim",
                        stan::model::index_uni(1)),
          stan::model::rvalue(ylim, "ylim", stan::model::index_uni(2)), lp__,
          nind, ntime);
      std::vector<std::vector<local_scalar_t__>> p0 =
        std::vector<std::vector<local_scalar_t__>>(ntime,
          std::vector<local_scalar_t__>(nrec, DUMMY_VAR__));
      local_scalar_t__ sigma = DUMMY_VAR__;
      std::vector<std::vector<std::vector<local_scalar_t__>>> d =
        std::vector<std::vector<std::vector<local_scalar_t__>>>(nind,
          std::vector<std::vector<local_scalar_t__>>(nrec,
            std::vector<local_scalar_t__>(ntime, DUMMY_VAR__)));
      std::vector<std::vector<local_scalar_t__>> td =
        std::vector<std::vector<local_scalar_t__>>(ntest,
          std::vector<local_scalar_t__>(nrec, DUMMY_VAR__));
      current_statement__ = 9;
      sigma = stan::math::sqrt((1 / (2 * alpha1)));
      current_statement__ = 14;
      for (int s = 1; s <= ntest; ++s) {
        current_statement__ = 12;
        for (int j = 1; j <= nrec; ++j) {
          current_statement__ = 10;
          stan::model::assign(td,
            stan::math::sqrt(
              (stan::math::square(
                 (stan::model::rvalue(testX, "testX",
                    stan::model::index_uni(s)) -
                 stan::model::rvalue(recX, "recX", stan::model::index_uni(j))))
              +
              stan::math::square(
                (stan::model::rvalue(testY, "testY",
                   stan::model::index_uni(s)) -
                stan::model::rvalue(recY, "recY", stan::model::index_uni(j)))))),
            "assigning variable td", stan::model::index_uni(s),
            stan::model::index_uni(j));
        }
      }
      current_statement__ = 22;
      for (int t = 1; t <= ntime; ++t) {
        current_statement__ = 20;
        for (int j = 1; j <= nrec; ++j) {
          current_statement__ = 18;
          for (int i = 1; i <= nind; ++i) {
            current_statement__ = 15;
            stan::model::assign(d,
              stan::math::sqrt(
                (stan::math::square(
                   (stan::model::rvalue(sx, "sx", stan::model::index_uni(i),
                      stan::model::index_uni(t)) -
                   stan::model::rvalue(recX, "recX",
                     stan::model::index_uni(j)))) +
                stan::math::square(
                  (stan::model::rvalue(sy, "sy", stan::model::index_uni(i),
                     stan::model::index_uni(t)) -
                  stan::model::rvalue(recY, "recY", stan::model::index_uni(j)))))),
              "assigning variable d", stan::model::index_uni(i),
              stan::model::index_uni(j), stan::model::index_uni(t));
            current_statement__ = 16;
            stan::model::assign(p0,
              stan::math::inv_logit(
                stan::model::rvalue(alpha0, "alpha0",
                  stan::model::index_uni(t), stan::model::index_uni(j))),
              "assigning variable p0", stan::model::index_uni(t),
              stan::model::index_uni(j));
          }
        }
      }
      {
        current_statement__ = 23;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(
                         stan::model::rvalue(alpha0, "alpha0",
                           stan::model::index_uni(ntime),
                           stan::model::index_uni(nrec)), 0, 2.5));
        current_statement__ = 24;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(alpha1, 0, 2.5));
        current_statement__ = 34;
        for (int t = 1; t <= ntime; ++t) {
          current_statement__ = 32;
          for (int j = 1; j <= nrec; ++j) {
            current_statement__ = 27;
            for (int s = 1; s <= ntest; ++s) {
              current_statement__ = 25;
              lp_accum__.add(stan::math::binomial_lpmf<propto__>(
                               stan::model::rvalue(test, "test",
                                 stan::model::index_uni(s),
                                 stan::model::index_uni(j),
                                 stan::model::index_uni(t)), ntrans,
                               (stan::model::rvalue(p0, "p0",
                                  stan::model::index_uni(t),
                                  stan::model::index_uni(j)) *
                               stan::math::exp((-(alpha1) *
                                 stan::math::square(
                                   stan::model::rvalue(td, "td",
                                     stan::model::index_uni(s),
                                     stan::model::index_uni(j))))))));
            }
            current_statement__ = 30;
            for (int i = 1; i <= nind; ++i) {
              current_statement__ = 28;
              lp_accum__.add(stan::math::binomial_lpmf<propto__>(
                               stan::model::rvalue(y, "y",
                                 stan::model::index_uni(i),
                                 stan::model::index_uni(j),
                                 stan::model::index_uni(t)), ntrans,
                               (stan::model::rvalue(p0, "p0",
                                  stan::model::index_uni(t),
                                  stan::model::index_uni(j)) *
                               stan::math::exp((-(alpha1) *
                                 stan::math::square(
                                   stan::model::rvalue(d, "d",
                                     stan::model::index_uni(i),
                                     stan::model::index_uni(j),
                                     stan::model::index_uni(t))))))));
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "model_COA_Tag_Integrated_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto alpha0 =
        in__.template read_constrain_lub<
          std::vector<std::vector<local_scalar_t__>>, jacobian__>(-(5), 5,
          lp__, ntime, nrec);
      current_statement__ = 2;
      auto alpha1 =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 3;
      auto sx =
        in__.template read_constrain_lub<
          std::vector<std::vector<local_scalar_t__>>,
          jacobian__>(stan::model::rvalue(xlim, "xlim",
                        stan::model::index_uni(1)),
          stan::model::rvalue(xlim, "xlim", stan::model::index_uni(2)), lp__,
          nind, ntime);
      current_statement__ = 4;
      auto sy =
        in__.template read_constrain_lub<
          std::vector<std::vector<local_scalar_t__>>,
          jacobian__>(stan::model::rvalue(ylim, "ylim",
                        stan::model::index_uni(1)),
          stan::model::rvalue(ylim, "ylim", stan::model::index_uni(2)), lp__,
          nind, ntime);
      std::vector<std::vector<double>> p0 =
        std::vector<std::vector<double>>(ntime,
          std::vector<double>(nrec, std::numeric_limits<double>::quiet_NaN()));
      double sigma = std::numeric_limits<double>::quiet_NaN();
      std::vector<std::vector<std::vector<double>>> d =
        std::vector<std::vector<std::vector<double>>>(nind,
          std::vector<std::vector<double>>(nrec,
            std::vector<double>(ntime,
              std::numeric_limits<double>::quiet_NaN())));
      std::vector<std::vector<double>> td =
        std::vector<std::vector<double>>(ntest,
          std::vector<double>(nrec, std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
          out__.write(alpha0[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      out__.write(alpha1);
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
          out__.write(sx[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
          out__.write(sy[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 9;
      sigma = stan::math::sqrt((1 / (2 * alpha1)));
      current_statement__ = 14;
      for (int s = 1; s <= ntest; ++s) {
        current_statement__ = 12;
        for (int j = 1; j <= nrec; ++j) {
          current_statement__ = 10;
          stan::model::assign(td,
            stan::math::sqrt(
              (stan::math::square(
                 (stan::model::rvalue(testX, "testX",
                    stan::model::index_uni(s)) -
                 stan::model::rvalue(recX, "recX", stan::model::index_uni(j))))
              +
              stan::math::square(
                (stan::model::rvalue(testY, "testY",
                   stan::model::index_uni(s)) -
                stan::model::rvalue(recY, "recY", stan::model::index_uni(j)))))),
            "assigning variable td", stan::model::index_uni(s),
            stan::model::index_uni(j));
        }
      }
      current_statement__ = 22;
      for (int t = 1; t <= ntime; ++t) {
        current_statement__ = 20;
        for (int j = 1; j <= nrec; ++j) {
          current_statement__ = 18;
          for (int i = 1; i <= nind; ++i) {
            current_statement__ = 15;
            stan::model::assign(d,
              stan::math::sqrt(
                (stan::math::square(
                   (stan::model::rvalue(sx, "sx", stan::model::index_uni(i),
                      stan::model::index_uni(t)) -
                   stan::model::rvalue(recX, "recX",
                     stan::model::index_uni(j)))) +
                stan::math::square(
                  (stan::model::rvalue(sy, "sy", stan::model::index_uni(i),
                     stan::model::index_uni(t)) -
                  stan::model::rvalue(recY, "recY", stan::model::index_uni(j)))))),
              "assigning variable d", stan::model::index_uni(i),
              stan::model::index_uni(j), stan::model::index_uni(t));
            current_statement__ = 16;
            stan::model::assign(p0,
              stan::math::inv_logit(
                stan::model::rvalue(alpha0, "alpha0",
                  stan::model::index_uni(t), stan::model::index_uni(j))),
              "assigning variable p0", stan::model::index_uni(t),
              stan::model::index_uni(j));
          }
        }
      }
      if (emit_transformed_parameters__) {
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
            out__.write(p0[(sym2__ - 1)][(sym1__ - 1)]);
          }
        }
        out__.write(sigma);
        current_statement__ = 7;
        for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= nrec; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= nind; ++sym3__) {
              out__.write(d[(sym3__ - 1)][(sym2__ - 1)][(sym1__ - 1)]);
            }
          }
        }
        current_statement__ = 8;
        for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= ntest; ++sym2__) {
            out__.write(td[(sym2__ - 1)][(sym1__ - 1)]);
          }
        }
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      std::vector<std::vector<local_scalar_t__>> alpha0 =
        std::vector<std::vector<local_scalar_t__>>(ntime,
          std::vector<local_scalar_t__>(nrec, DUMMY_VAR__));
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
          current_statement__ = 1;
          alpha0[(sym2__ - 1)][(sym1__ - 1)] = in__.read<local_scalar_t__>();
        }
      }
      out__.write_free_lub(-(5), 5, alpha0);
      local_scalar_t__ alpha1 = DUMMY_VAR__;
      current_statement__ = 2;
      alpha1 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha1);
      std::vector<std::vector<local_scalar_t__>> sx =
        std::vector<std::vector<local_scalar_t__>>(nind,
          std::vector<local_scalar_t__>(ntime, DUMMY_VAR__));
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
          current_statement__ = 3;
          sx[(sym2__ - 1)][(sym1__ - 1)] = in__.read<local_scalar_t__>();
        }
      }
      out__.write_free_lub(stan::model::rvalue(xlim, "xlim",
                             stan::model::index_uni(1)),
        stan::model::rvalue(xlim, "xlim", stan::model::index_uni(2)), sx);
      std::vector<std::vector<local_scalar_t__>> sy =
        std::vector<std::vector<local_scalar_t__>>(nind,
          std::vector<local_scalar_t__>(ntime, DUMMY_VAR__));
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
          current_statement__ = 4;
          sy[(sym2__ - 1)][(sym1__ - 1)] = in__.read<local_scalar_t__>();
        }
      }
      out__.write_free_lub(stan::model::rvalue(ylim, "ylim",
                             stan::model::index_uni(1)),
        stan::model::rvalue(ylim, "ylim", stan::model::index_uni(2)), sy);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha0", "double",
        std::vector<size_t>{static_cast<size_t>(ntime),
          static_cast<size_t>(nrec)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "alpha1", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "sx", "double",
        std::vector<size_t>{static_cast<size_t>(nind),
          static_cast<size_t>(ntime)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sy", "double",
        std::vector<size_t>{static_cast<size_t>(nind),
          static_cast<size_t>(ntime)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<std::vector<local_scalar_t__>> alpha0 =
        std::vector<std::vector<local_scalar_t__>>(ntime,
          std::vector<local_scalar_t__>(nrec, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> alpha0_flat__;
        current_statement__ = 1;
        alpha0_flat__ = context__.vals_r("alpha0");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
            stan::model::assign(alpha0, alpha0_flat__[(pos__ - 1)],
              "assigning variable alpha0", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_lub(-(5), 5, alpha0);
      local_scalar_t__ alpha1 = DUMMY_VAR__;
      current_statement__ = 2;
      alpha1 = context__.vals_r("alpha1")[(1 - 1)];
      out__.write_free_lb(0, alpha1);
      std::vector<std::vector<local_scalar_t__>> sx =
        std::vector<std::vector<local_scalar_t__>>(nind,
          std::vector<local_scalar_t__>(ntime, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> sx_flat__;
        current_statement__ = 3;
        sx_flat__ = context__.vals_r("sx");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
            stan::model::assign(sx, sx_flat__[(pos__ - 1)],
              "assigning variable sx", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_lub(stan::model::rvalue(xlim, "xlim",
                             stan::model::index_uni(1)),
        stan::model::rvalue(xlim, "xlim", stan::model::index_uni(2)), sx);
      std::vector<std::vector<local_scalar_t__>> sy =
        std::vector<std::vector<local_scalar_t__>>(nind,
          std::vector<local_scalar_t__>(ntime, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> sy_flat__;
        current_statement__ = 4;
        sy_flat__ = context__.vals_r("sy");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
            stan::model::assign(sy, sy_flat__[(pos__ - 1)],
              "assigning variable sy", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_lub(stan::model::rvalue(ylim, "ylim",
                             stan::model::index_uni(1)),
        stan::model::rvalue(ylim, "ylim", stan::model::index_uni(2)), sy);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha0", "alpha1", "sx", "sy"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"p0", "sigma", "d", "td"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    ntime),
                                                 static_cast<size_t>(nrec)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(nind),
                  static_cast<size_t>(ntime)},
                std::vector<size_t>{static_cast<size_t>(nind),
                  static_cast<size_t>(ntime)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(ntime),
               static_cast<size_t>(nrec)}, std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(nind),
               static_cast<size_t>(nrec), static_cast<size_t>(ntime)},
             std::vector<size_t>{static_cast<size_t>(ntest),
               static_cast<size_t>(nrec)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
        param_names__.emplace_back(std::string() + "alpha0" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "alpha1");
    for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
        param_names__.emplace_back(std::string() + "sx" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
        param_names__.emplace_back(std::string() + "sy" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
          param_names__.emplace_back(std::string() + "p0" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      param_names__.emplace_back(std::string() + "sigma");
      for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= nrec; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= nind; ++sym3__) {
            param_names__.emplace_back(std::string() + "d" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= ntest; ++sym2__) {
          param_names__.emplace_back(std::string() + "td" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
        param_names__.emplace_back(std::string() + "alpha0" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "alpha1");
    for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
        param_names__.emplace_back(std::string() + "sx" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= nind; ++sym2__) {
        param_names__.emplace_back(std::string() + "sy" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= ntime; ++sym2__) {
          param_names__.emplace_back(std::string() + "p0" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      param_names__.emplace_back(std::string() + "sigma");
      for (int sym1__ = 1; sym1__ <= ntime; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= nrec; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= nind; ++sym3__) {
            param_names__.emplace_back(std::string() + "d" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= nrec; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= ntest; ++sym2__) {
          param_names__.emplace_back(std::string() + "td" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha0\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(ntime) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(nrec) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"parameters\"},{\"name\":\"alpha1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sx\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(nind) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(ntime) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"parameters\"},{\"name\":\"sy\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(nind) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(ntime) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"parameters\"},{\"name\":\"p0\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(ntime) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(nrec) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"transformed_parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"d\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(nind) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(nrec) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(ntime) + ",\"element_type\":{\"name\":\"real\"}}}},\"block\":\"transformed_parameters\"},{\"name\":\"td\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(ntest) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(nrec) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha0\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(ntime) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(nrec) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"parameters\"},{\"name\":\"alpha1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sx\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(nind) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(ntime) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"parameters\"},{\"name\":\"sy\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(nind) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(ntime) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"parameters\"},{\"name\":\"p0\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(ntime) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(nrec) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"transformed_parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"d\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(nind) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(nrec) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(ntime) + ",\"element_type\":{\"name\":\"real\"}}}},\"block\":\"transformed_parameters\"},{\"name\":\"td\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(ntest) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(nrec) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((ntime * nrec) + 1) + (nind * ntime)) +
      (nind * ntime));
    const size_t num_transformed = emit_transformed_parameters * (((((ntime *
      nrec) + 1) + (nind * (nrec * ntime))) + (ntest * nrec)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((ntime * nrec) + 1) + (nind * ntime)) +
      (nind * ntime));
    const size_t num_transformed = emit_transformed_parameters * (((((ntime *
      nrec) + 1) + (nind * (nrec * ntime))) + (ntest * nrec)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_COA_Tag_Integrated_namespace::model_COA_Tag_Integrated;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_COA_Tag_Integrated_namespace::profiles__;
}
#endif
#endif
